[GILJOB-50] 랜딩페이지 완성
YAPP-19th/Web-Team-1-Frontend pull request #10
Opened 2021-11-17 09:24 UTC by kyoung-jnn

## Summary

- 랜딩페이지 완성
- 텍스트 컴포넌트 수정

## Detail

랜딩페이지 전체적으로 완성했습니다.
폴더 구조는 아직 정확히 어떻게 잡아야할지 몰라서 임의로 생성하여 진행했습니다.

Count up 구현중 지금 텍스트 컴포넌트에는 ref 를 전달하지 못 해서 텍스트 컴포넌트를 수정했습니다.

2021-11-17 09:31 UTC, kyoung-jnn commented on src/atoms/Text/Text.tsx
> +      children,
ref 를 props로 받기위해 forwardRef 로 감싸줬습니다.

2021-11-17 09:31 UTC, kyoung-jnn commented on src/atoms/Text/Text.tsx
>  export default Text;
forwardRef로 감싸면 displayName이 없다고 eslint 오류가 나서 지정했습니다.

2021-11-17 09:31 UTC, kyoung-jnn commented on src/pages/Landing/templates/Main/style.scss
> +
현재 텍스트 컴포넌트에서 size, weight를 지원하지 않는 부분은 따로 설정해줬습니다.

아마 랜딩페이지에서만 특수하게 **엄청 큰 글자와 얇은 글자**가 존재해서
텍스트 컴포넌트를 크게 수정할 필요는 없어보입니다.

2021-11-17 09:31 UTC, kyoung-jnn commented on src/atoms/Text/Text.tsx
> +        )}
현재 `line-height` 는 1.5, 2rem 밖에 없어서
2rem 이상으로 텍스트를 설정하면 크기가 안맞습니다.
이 부분은 수정해야할 듯 합니다!

2021-11-17 09:50 UTC, raejoonee commented on src/atoms/Text/Text.tsx
> +        )}
네 공통 CSS 부분 수정해야 할 것 같네요

2021-11-17 12:41 UTC, LeeJuhae approved these changes
👍

2021-11-19 14:08 UTC, raejoonee commented on src/atoms/Text/Text.tsx
> +      children,
👍

2021-11-19 14:37 UTC, raejoonee approved these changes
`useScrollCount` Hook의 역할이 뭔지, 어떤 방식으로 동작하는지, 어떻게 사용하면 되는지 주석을 달아주시면 좋을 것 같습니다! 한번에 파악하기가 어려웠어요 😢

2021-11-19 14:37 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +    }
## 질문
훅 내부에서 변수에 새로운 값을 할당하면 매 렌더링마다 해당 할당이 초기화될 것 같은데 이런 방식으로 코드를 작성한 다른 이유가 있나요? `observer` 변수를 `useRef` 훅을 써서 값을 할당해주고 `useEffect` 내부에서 변수를 그대로 사용하면 안되나요? 🤔

2021-11-19 14:37 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +    [start, end, countTime, spanElement],
20번 라인에서 `observer`가 사용되고 있어서 `observer`도 의존 배열에 추가되어야 할 것 같습니다. 그런데 의존 배열에 추가하려면, 위에서 말씀드린 대로 미리 변수에 값이 할당되어야 합니다. 예를 들면 `useRef`를 쓰는 방식 등을 통해서요!

2021-11-19 14:37 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +  const countTime = Math.abs(Math.floor(duration / (end - start)));
`countTime`이 interval 주기를 설정하기 위해서만 사용되는 변수가 맞나요?

2021-11-19 14:37 UTC, raejoonee commented on src/pages/Landing/templates/Count/index.tsx
> +    2: useScrollCount(0, 80),
직전 질문에서 이어지는 질문인데, interval 주기가 다른 `ScrollCount`를 사용해야 하는 이유가 있는 건가요?

2021-11-19 16:40 UTC, kyoung-jnn commented on src/hooks/useScrollCount.ts
> +  const countTime = Math.abs(Math.floor(duration / (end - start)));
네 맞습니다!
생각해보니 랜딩 페이지에서는 딱히 각각의 주기를 설정할 필요가 없겠네요..
이 부분은 상수로 변경하겠습니다! `2초`

2021-11-19 17:08 UTC, kyoung-jnn commented on src/hooks/useScrollCount.ts
> +    }
```
const observer: any = useRef<any>(null);
```
이런 방식을 말씀하시는걸까요??

2021-11-19 17:19 UTC, kyoung-jnn commented on src/hooks/useScrollCount.ts
> +      }
이 부분에서 observer가 감지되서 카운트가 올라가는 상황에
observer가 카운트가 끝나기 전까지 계속해서 감지되는 문제를 발견해서 수정하겠습니다~

2021-11-19 23:46 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +  const countTime = Math.abs(Math.floor(duration / (end - start)));
넵 상수로 변경하고 변수 이름도 바꿔주면 좋을 것 같습니다 감사합니다 🙇

2021-11-20 00:09 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +  const countTime = Math.abs(Math.floor(duration / (end - start)));
@kyoung-jnn 지금 보니까 스크롤 이벤트는 아래 숫자들이 올라가는 이벤트 구현하기 위해서만 사용되는 게 맞나요? 맞다면 있긴 해야 할 것 같아서 회의 때 다시 정해야 할 것 같습니다!

2021-11-20 01:04 UTC, raejoonee requested changes
현재 전체적인 폴더 구조에서 네이밍이 `Content`, `Contents` 등으로 되어 있어서 사실상 직관적인 구분이 불가능한 것 같습니다 😢 이 부분도 수정해야 할 것 같아요

2021-11-20 01:04 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +            observer.disconnect();
`disconnect` 대신 `unobserve`를 사용하는 것이 좋을 것 같고, 훅 외부에서 특정 ref에 대해 `observe`와 `unobserve`하는 callback을 넘겨주는 방식도 생각해볼 만 한 것 같습니다!

2021-11-20 01:04 UTC, raejoonee commented on src/hooks/useScrollCount.ts
> +          current.innerHTML = currentNumber.toString();
훅 내부에서 (사실 훅 외부에서도) `innerHTML`을 사용하면 위험할 것 같습니다 ❌

2021-11-20 13:21 UTC, raejoonee approved these changes

2021-11-20 13:23 UTC, merged