Feature/login
YAPP-19th/Web-Team-1-Frontend pull request #17
Opened 2021-11-23 08:43 UTC by kyoung-jnn

## Summary

- 로그인 페이지를 구현했습니다.

## Detail

- png 파일의 사용을 위해 index.d.ts에 추가했습니다. 5497ad5
- Login 페이지를 완성했습니다. 헤더와 푸터를 `Based Wrapper`로 만들고 감싸줬습니다. 5b0d732

2021-11-23 08:45 UTC, kyoung-jnn commented on src/pages/Based/index.tsx
> +export default Based;
Header와 Footer가 페이지 구현할때 계속 쓰일 것 같아서
따로 Wrapper처럼 쓸 수 있게 구현했는데
어떻게 생각하시나요?
만약 괜찮으시면 style도 기존 Header, Footer에서 옮겨놓겠습니다.

2021-11-23 08:47 UTC, raejoonee commented
혹시 `Based` 페이지가 무슨 페이지인가요? 네이밍을 이렇게 정한 이유가 있나요? 무슨 역할을 하는 페이지인지 이름만 보고는 알 수가 없네요 😢

2021-11-23 08:48 UTC, raejoonee commented on src/pages/Based/index.tsx
> +export default Based;
Header와 Footer는 길잡 모든 페이지에서 항상 최상단, 최하단에 있는 컴포넌트 아닌가요?
페이지 내부에서 사용하고 있는 이유가 뭔지 알 수 있나요?

2021-11-23 08:49 UTC, raejoonee commented on src/pages/Based/index.tsx
> +export default Based;
이렇게 사용하지 않고, 그냥 라우팅을 Header와 Footer와 별개로 진행하면 되지 않을까요?

2021-11-23 08:52 UTC, kyoung-jnn commented on src/pages/Based/index.tsx
> +export default Based;
로그인 페이지에서는 `Header` 사용이 안되서 이렇게 구현해봤습니다
홈페이지 주소를 이용해서 헤더를 감춰버리는거랑 이렇게 wrapper 처럼 쓰는거랑 고민했는데
어떻게 하는게 나을까요?

2021-11-23 08:54 UTC, raejoonee requested changes

2021-11-23 08:54 UTC, raejoonee commented on src/styles/_color.scss
> +
```suggestion
// enterprise
$kakao: #ffd43b;

```
혹시 변수 이름 이렇게 바꿔주실 수 있나요? 저희가 현재 사용하는 컬러는 기본 노랑이라기보다는 카카오 노랑이라고 생각해서요 😊 
추후 `facebook`, `google` 등이 추가될 때 각 enterprise별로 컬러 코드를 저장하기에도 편리합니다! 🎉 
선언된 위치도 색상이 모여있는 곳 말고 다른 위치로 옮겨주시면 감사하겠습니다 🙇

2021-11-23 08:54 UTC, kyoung-jnn commented on src/styles/_color.scss
> +
넵

2021-11-23 08:55 UTC, raejoonee commented on src/pages/Based/index.tsx
> +export default Based;
주소를 이용해서 감춘다는 것은, `Header` 컴포넌트가 react-router를 통해서 현재 주소를 읽어서 그 값에 따라 조건부 렌더링을 하겠다는 뜻인가요? 🤔

2021-11-23 14:42 UTC, raejoonee requested changes

2021-11-23 14:42 UTC, raejoonee commented on src/components/molecules/Header/index.tsx
> +  ) : null;
이 곳에서 삼항연산자를 쓴 것도 좋지만 `false`일 때 `null`이라면 `&&`를 쓰는 게 더 좋을 것 같아요!

2021-11-23 14:57 UTC, kyoung-jnn commented on src/components/molecules/Header/index.tsx
> +  ) : null;
컴포넌트 전체렌더링하고 관련있어서 삼항연산자 사용 안하면
return type 설정을 복잡하게 해야할 듯 하는데 어떻게 생각하시나용

---

https://ko.reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering

방금 찾았는데 null 자체를 반환해도 나쁘지는 않을 듯 합니다!

2021-11-23 15:04 UTC, raejoonee commented on src/components/molecules/Header/index.tsx
> +  ) : null;
오 좋네요 대박!! 👍

2021-11-24 08:17 UTC, raejoonee approved these changes

2021-11-24 10:40 UTC, LeeJuhae approved these changes
👍

2021-11-24 10:41 UTC, merged