Feature/profile
YAPP-19th/Web-Team-1-Frontend pull request #24
Opened 2021-11-27 10:56 UTC by LeeJuhae

## Summary
/profile 페이지의 Mypage 컴포넌트를 생성했습니다.

## Detail
Mypage 컴포넌트를 생성하며 아래 컴포넌트들을 생성했습니다.
- AchievementBadge
- AchiementIcon
- Box
- Form
- ProgressBar

2021-11-29 06:09 UTC, kyoung-jnn approved these changes
고생하셨습니다 ㅎㅎ

2021-11-29 06:09 UTC, kyoung-jnn commented on src/components/atoms/Form/form.stories.tsx
> +    <textarea defaultValue="안녕하세요, 저는 프론트앤드 개발자입니다. 제이쿼리, 자바스크립트 등에 관심이 많습니다. 현재 IT 업계 ABC회사에서 근무하고 있습니다 or 안녕하세요 저는 대학교 4학년 컴퓨터공학과 가나다라마바사입니다."></textarea>
공백 제거해야할 것 같아요!

2021-11-29 06:09 UTC, kyoung-jnn commented on src/pages/Profile/index.tsx
> +import './style.scss';
`@src` 경로로 바꿔야 할 듯 합니다

2021-11-29 06:09 UTC, kyoung-jnn commented on src/components/atoms/ProgressBar/index.tsx
> +  border-radius: 2.5rem;
`gil-blue` 색상 쓰면 될 것 같습니다.

2021-11-29 10:23 UTC, raejoonee requested changes

2021-11-29 10:23 UTC, raejoonee commented on src/components/molecules/Mypage/mypage.stories.tsx
> +  title: 'Pages/Profile/Mypage',
이 스토리는 `/profile` 경로에서 보이는 페이지를 보여주는 게 아니고, molecule 컴포넌트를 보여주는 거라서 아래와 같이 바꿔야 할 것 같습니다.
```suggestion
  title: 'Design System/Molecules/Mypage',
```

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/AchievementBadge/index.tsx
> +import AchievementIcon from '../AchievementIcon';
atom을 import할 때는 한 줄로 import하면 좋을 것 같습니다.

```suggestion
import { AchievementIcon, Text } from '@src/components/atoms';
```

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/AchievementBadge/index.tsx
> +  description,
`description`은 optional한 prop이기 때문에 기본값을 주어야 할 것 같습니다.

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/Box/box.stories.tsx
> +import { BoxProps } from '@src/components/atoms/Box';
```suggestion
import Box, { BoxProps } from '@src/components/atoms/Box';
```

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/Form/form.stories.tsx
> +import { FormProps } from '@src/components/atoms/Form';
```suggestion
import Form, { FormProps } from '@src/components/atoms/Form';
```

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/Form/index.tsx
> +import Text from '../Text';
```suggestion
import cn from 'classnames';
import { Text } from '@src/components/atoms';
```

2021-11-29 10:23 UTC, raejoonee commented on src/components/atoms/ProgressBar/index.tsx
> +  border-radius: 2.5rem;
아마 styled-components로 생성한 컴포넌트에서 SCSS custom variable을 사용하지 못해서 그런 것 같은데 사용 할 수 있나요?

2021-11-29 10:23 UTC, raejoonee commented on src/pages/Profile/index.tsx
> +import './style.scss';
```suggestion
import React from 'react';
import { Mypage } from '../../components/molecules';
import './style.scss';
```

2021-11-29 10:25 UTC, raejoonee commented
지금 Form 컴포넌트를 스토리북에서 보면 아래처럼 보이는데 의도한 건지 궁금합니다!
![image](https://user-images.githubusercontent.com/59731373/143851154-31ad52aa-73ba-4116-a6a9-03c3982f03d5.png)

2021-11-29 13:55 UTC, kyoung-jnn commented on src/components/atoms/ProgressBar/index.tsx
> +  border-radius: 2.5rem;
앗 맞네요! 아마 scss 변수를 사용할 수 있는 방법은 없을 것 같아요..
이 부분은 어쩔수 없겠네요 ㅠ

2021-12-03 08:17 UTC, raejoonee approved these changes

2021-12-03 08:18 UTC, kyoung-jnn approved these changes
경로 깔끔하네요 💪

2021-12-03 08:18 UTC, merged