[GILJOB-110] 프로필 페이지 개발 완료
YAPP-19th/Web-Team-1-Frontend pull request #35
Opened 2021-12-17 07:44 UTC by LeeJuhae

## Summary
- 프로필 페이지의 4개의 탭(프로필/퀘스트/로드맵/항해 업적)에 연결되는 컴포넌트 개발 완료

## Detail
- 현재 컴포넌트 작성에 사용한 모든 데이터는 더미 데이터입니다.
- 본 pr merge 이후 Mypage에서 닉네임, 자기소개 등을 변경할 수 있도록 추가 작업할 예정입니다.

2021-12-18 02:13 UTC, kyoung-jnn approved these changes
<img width="818" alt="스크린샷 2021-12-18 오전 11 10 40" src="https://user-images.githubusercontent.com/55469709/146625642-39cd0410-b380-4b89-8f4b-fb7631433728.png">

이 부분만 `grid`로 변경하면 깔끔할 것 같습니다.
고생하셨습니다 ㅎㅎ

2021-12-18 02:20 UTC, LeeJuhae commented
> <img alt="스크린샷 2021-12-18 오전 11 10 40" width="818" src="https://user-images.githubusercontent.com/55469709/146625642-39cd0410-b380-4b89-8f4b-fb7631433728.png">
> 
> 이 부분만 `grid`로 변경하면 깔끔할 것 같습니다. 고생하셨습니다 ㅎㅎ

네! 리뷰해주신 부분은 다음 pr때 반영하겠습니다!
Profile 컴포넌트 전반적인 수정(Mypage 컴포넌트 수정 등) 작업이 필요할 것 같아서 그때 수정하도록 하겠습니다.

2021-12-18 07:02 UTC, raejoonee requested changes
TabBar, ProfileQuestCard 컴포넌트 잘 만들었네요! 👏 
이 PR은 계속 수정사항 커밋한다고 했으니 Request changes 해두겠습니다.

2021-12-18 07:02 UTC, raejoonee commented on src/components/atoms/TabBar/tabBar.stories.tsx
> +  ],
```suggestion
  tabList: [
    {
      name: '프로필',
    },
    {
      name: '퀘스트',
    },
    {
      name: '로드맵',
    },
    {
      name: '항해 업적',
    },
  ],
  align: 'center',
  hasDivider: true,
  selected: 1,
```

2021-12-18 07:02 UTC, raejoonee commented on src/components/atoms/TabBar/tabBar.stories.tsx
> +    },
```suggestion
    hasDivider: {
      type: 'boolean',
    },
    selected: {
        type: 'number',
    },
```

2021-12-18 07:02 UTC, raejoonee commented on src/components/atoms/Box/index.tsx
> +  className = '',
👍

2021-12-18 07:02 UTC, raejoonee commented on src/pages/Profile/Mypage/index.tsx
> +            description={exp_achievement.list[0].description}
여기 타입 정의가 안 된 객체를 사용하고 있어서 에러가 발생할 확률이 있기 때문에 optional chaining 해야 할 것 같아요 🤔 
```suggestion
            id={exp_achievement?.list[0]?.id}
            title={exp_achievement?.list[0]?.title}
            description={exp_achievement?.list[0]?.description}
```

2021-12-18 07:02 UTC, raejoonee commented on src/pages/Profile/Mypage/index.tsx
> +            description={quest_achievement.list[0].description}
여기도 optional chaining

2021-12-18 07:43 UTC, LeeJuhae commented on src/pages/Profile/Mypage/index.tsx
> +            description={quest_achievement.list[0].description}
네! 리뷰 감사합니다! 수정하겠습니다💃🏻

2021-12-18 08:08 UTC, raejoonee approved these changes
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

2021-12-20 10:14 UTC, raejoonee commented
@LeeJuhae 님 #27 이슈 여기서 해결하시나요?

2021-12-20 10:15 UTC, LeeJuhae commented
네! Form 컴포넌트 삭제했어요!

2021-12-20 15:49 UTC, merged